# Generated by Django 5.2.4 on 2025-07-04 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Введите название",
                        max_length=100,
                        null=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="materials/preview/course",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Введите описание",
                        max_length=150,
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Введите название урока",
                        max_length=100,
                        null=True,
                        verbose_name="Название урока",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Введите описание урока",
                        max_length=150,
                        null=True,
                        verbose_name="Описание урока",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="materials/preview/lesson",
                        verbose_name="Превью урока",
                    ),
                ),
                (
                    "link_to_video",
                    models.CharField(
                        blank=True,
                        help_text="Загрузите ссылку на видео",
                        max_length=100,
                        null=True,
                        verbose_name="Ссылка на видео",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
